services:
  db:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .db.env
    environment:
      - POSTGRES_DB=nokroner_development
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .pgadmin.env
    ports:
      - "3001:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

  rails:
    container_name: rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
      - .db.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nokroner_development
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: ./app
          action: sync
          target: /rails/app
          initial_sync: true
        - path: ./config
          action: sync+restart
          target: /rails/config
          initial_sync: true
        - path: ./db
          action: sync+restart
          target: /rails/db
        - path: Gemfile.lock
          action: rebuild

  rails_worker:
    container_name: worker
    command: "bin/jobs start"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .db.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nokroner_production
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: ./app
          action: sync
          target: /rails/app
        - path: ./config/recurring.yml
          action: sync+restart
          target: /rails/config/recurring.yml
        - path: Gemfile.lock
          action: rebuild

volumes:
  pg_data:
  pgadmin_data:
